### ISSUE TITLE
mb > ᵐb

### ISSUE THREAD

**Issue by tihomirrangelov** [lexibank/abvdoceanic#34]
In some transcriptions I find sequences of <mb>, which should be changed to <ᵐb>. However the mb sequence does not appear in the orthography profile of e.g. BurmbarFartavo. Can I add a line like thisː
`mb	ᵐb`
If yes,
Do I need to count the number of occurrences and include them in the third column?
Does it matter if mb appears in the beginning or end of a word, meaning would I need to make separate entries for those cases, using a caret?

**Comment by maryewal** [comment]
Yes, add a line if there is no ⁿb already listed. Are all m-b sequences are actually prenasalized b, or are there clear instances where m-b is truly m-b? 

`Does it matter if mb appears in the beginning or end of a word, meaning would I need to make separate entries for those cases, using a caret?`
Do you mean that mb is only prenasalized initially or finally, but not medially? If no, and mb is always ⁿb, then no you don't need to address this in any way. If yes, you'll need to indicate this so that only m-b sequences in these conditions will become ⁿb . If the latter is true, then I think you will also want to be sure to have a line:

`mb > m b`

I don't think you need to list the number of occurrences when adding a new segment (can you confirm @LinguList?)

**Comment by LinguList** [comment]
No you can leave that field blank, just Graphemes and IPA must be filled.

**Comment by tihomirrangelov** [comment]
> Do you mean that mb is only prenasalized initially or finally, but not medially?

I mean that very often we have more than one line for the same grapheme, depending on whether it is in the beginning, end or middle of the word, e.g. in the same profile we haveː
```
^a	a	9
a$	a	3
a	a	139

```
In this sense, if I simply make one entry:
`mb   ⁿb`
I worry that the algorithm might not catch word-initial and word-final mb sequences. 
Is that so, @LinguList? Would a single entry suffice or would I need to make separate entries for the relevant positions within the word?

**Comment by LinguList** [comment]
Please make separate entries for initial ^mb and mb, but final is not 
needed, unless it differs, due to the way the algorithm proceeds.

**Comment by tihomirrangelov** [comment]
Thank you all
