### ISSUE TITLE
Consonant clusters

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/abvdoceanic#50]
There are a couple of very long consonant clusters which should be checked. @SimonGreenhill Maybe we can provide some easy fixes for those through the orthography profiles?

| Language_ID | Length | Cluster | Words |
|:-----------------------------------|---------:|:--------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nalik_368 | 3 | n g t | r a n g t a n g a n // rangtangan // m a n g t u l // mangtul |
| HaliaSelau_647 | 3 | r n g | n g o r n g o r o // ngorngoro |
| Patpatar_178 | 3 | r n g | n g a r n g a r // ngarngar |
| Avava_456 | 3 | r n g | n g a r n g a r // ngarngar |
| AngavaeDixonReef_1238 | 4 | t n t n | t n t n // -tntn |
| Avava_456 | 4 | t n t n | t n t n // tntn |
| Neveei_484 | 4 | t n t n | t n t n // tntn |
| NindeLawa_1217 | 4 | t n t n | t n t n // -tntn |
| NombotkoteUsusMelkin_1230 | 4 | t n t n | t n t n // -tntn // t n t n // -tntn |
| Kokota_365 | 4 | ɣ ŋ ɣ ŋ | ɣ ŋ ɣ ŋ a u // ɣŋɣŋau |
| Mangseng_1335 | 4 | k n g r | ŋ r e k n g r e k // ŋrekngrek |
| Nahavaq_453 | 4 | n v y/j n | t i n v y/j n // tinvyn |
| Roria_1006 | 4 | n ts n t | n a n ts n t a r a ⁿp // nantˢntaraᵐp |
| SakaoPortOlry_230 | 4 | β y/j l j/dʒ | a β y/j l j/dʒ ɛ + ɣ // aβyljɛ-ɣ // a β y/j l j/dʒ a + n // aβylja-n |
| SakaoPortOlry_230 | 4 | r s y/j m | k ɔ r s y/j m // kɔrsym |
| Iaai_471 | 5 | y/j ɲ k y/j m | y/j ɲ k y/j m e // yñkyme |
| Nahavaq_453 | 5 | m b y/j s y/j | m b y/j s y/j // mbysy- |
| Nahavaq_453 | 5 | m b y/j n ʔ | l e m b y/j n ʔ a j/dʒ // lembynʔaj |
| NatiWindua_1229 | 5 | β y/j l y/j n | n o + s i β y/j l y/j n + v a r a n // no-siβylyn_varan |
| SakaoPortOlry_230 | 6 | β c/ts ɣ β c/ts ɣ | β c/ts ɣ β c/ts ɣ // βcɣβcɣ |
| SakaoPortOlry_230 | 6 | β y/j t β y/j t | β y/j t β y/j t // βytβyt |
| SakaoPortOlry_230 | 6 | β y/j l β y/j l | β y/j l β y/j l // βylβyl |
| Nahavaq_453 | 8 | m b y/j ʔ m b y/j ʔ | m b y/j ʔ m b y/j ʔ // mbyʔmbyʔ |

**Comment by SimonGreenhill** [comment]
@tihomirrangelov  -- can you please take a look at these?

**Comment by tihomirrangelov** [comment]
- The first four, involving 'n g', my guess is these are not two segments, but one, namely ŋ, in some cases the consonant clusters span across morpheme boundaries, as some of these examples clearly involve reduplication, but then there is nothing unusual.
- AngavaeDixonReef_1238. I was able to verify this against the sound file in VV. It seems like the transcription is wrong. I would transcribe this as [tu-titn̩] (with the final n syllabic). 
- Avava_456. This language allows up to five-consonant clusters word finally, but the sonorants in such clusters are usually syllabic (Crowley 2006). So the proper transcription should be [tn̩tn̩] where these are two syllables. This is also my impression from the audio in VV. The same seems to be the case with the other three varieties with this cluster.
- Kokota_365. Probably syllabic ŋ
- Mangseng_1335. Clearly the 'n g' should be ŋ
- Nahavaq_453. I couldn't find this example in VV to hear it, but if we choose 'y', rather than 'j', then this is phonotactically very simple, i.e no consonant clusters to write home aboutː CVC.CVC
- Roria_1006. There are no descriptions or sound files for this languages, but looking at the wordlist, my best guess is that  'n ts' is one prenasalized affricate segment [ⁿt͡s]. 'nt' could be either a [ⁿd] or a n+t cluster in a syllable onset. Possibly, but less likely, a prenasalized t.
- SakaoPortOlry_230. /y/ is a vowel here. 
- Iaai_471. /y/ is a vowel
- Nahavaq_453. /y/ is a vowel. I would also bet that /mb/ is actually a prenasalized b than a cluster.
- NatiWindua_1229: /y/ is a vowel.
- SakaoPortOlry_230. βcɣβcɣ - this is probably a mistake in transcription. I have collected data on this language and for 'good' I have βɔɣβɔɣ, where ɔ is a vowel. In the other two examples, /y/ is a vowel.
- Nahavaq_453. /y/ is a vowel. I also bet that mb is a prenasalized b, rather than a cluster.

**Comment by FredericBlum** [comment]
Most of those cases (ŋ, y) can be adopted through the orthography profiles. Do you have updated versions on some database, or are the ones in this repository the most up-to-date ones?

Can I change the /mb/ occurrences to prenasaliyzed /b/ in the languages with such clusters? I would then tag you in order to revise the mappings and double-check on the changes.

How can we fix the transcription errors? Manual resolving of transcription errors here and in the database on your side at the same time?

**Comment by tihomirrangelov** [comment]
Regarding mb, as long as a language has a prenasalisation contrast, it is a safe bet to go for a prenasalised b.
